--------------------------------
---------- PART 1 --------------
--------------------------------

--SELECT * into TEST_CUSTOMER from CUSTOMER;
SELECT * FROM dbo.ORDER_LINE OL INNER JOIN dbo.ORDERS O ON (O.ORDER_NUM = OL.ORDER_NUM);
SELECT * FROM dbo.ORDERS;
SELECT * FROM dbo.ORDER_LINE;

WITH ORDER_BALANCE as (
SELECT CUSTOMER_NUM, SUM(OL.NUM_ORDERED * OL.QUOTED_PRICE) as NEW_BALANCE
FROM dbo.ORDERS O 	INNER JOIN dbo.ORDER_LINE OL ON (OL.ORDER_NUM = O.ORDER_NUM)
GROUP BY O.CUSTOMER_NUM)
UPDATE TC
SET TC.BALANCE = OB.NEW_BALANCE
FROM   TEST_CUSTOMER TC
INNER JOIN ORDER_BALANCE OB
ON (OB.CUSTOMER_NUM = TC.CUSTOMER_NUM);

--------------------------------
---------- PART 2 --------------
--------------------------------

CREATE TRIGGER Update_Balance
ON dbo.ORDER_LINE
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
IF COLUMNS_UPDATED(NUM_ORDERED) 
BEGIN
UPDATE TC
	SET TC.BALANCE = NUM_ORDERED * QUOTED_PRICE
FROM   TEST_CUSTOMER TC
	 INNER JOIN dbo.ORDERS O ON (O.CUSTOMER_NUM = TC.CUSTOMER_NUM)
WHERE O.ORDER_NUM = ORDER_NUM;
END

--------------------------------
---------- PART 3 --------------
--------------------------------

UPDATE ORDER_LINE
SET NUM_ORDERED = NUM_ORDERED + 1, QUOTED_PRICE = QUOTED_PRICE + 10.00
WHERE ORDER_NUM IN(51608);

SELECT * FROM dbo.ORDERS;
SELECT * FROM dbo.ORDER_LINE;
SELECT * FROM dbo.CUSTOMER;